openapi: 3.0.3
info:
  title: BarbarianFoodAPI
  description: 'example'
  version: 1.0.0
paths:
  /auth/signup:
    post:
      tags:
        - auth
      description: Endpoint used to create an account
      operationId: signUp
      requestBody:
        description: Sign up request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
        '422':
          description: Data is incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/signin:
    post:
      tags:
        - auth
      description: Endpoint used to access existing account
      operationId: signIn
      requestBody:
        description: Sign in request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
        '422':
          description: Data is incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /settings/payment:
    post:
      tags:
        - settings
      description: Endpoint used to edit payment settings
      operationId: editPaymentInformation
      requestBody:
        description: Payment settings request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentSettingsRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
        '422':
          description: Data is incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /settings/profile:
    post:
      tags:
        - settings
      description: Endpoint used to edit profile settings
      operationId: editProfileInformation
      requestBody:
        description: Profile settings request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileSettingsRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
        '422':
          description: Data is incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    SignUpRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
        surname:
          type: string
    SignInRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    PaymentSettingsRequest:
      type: object
      properties:
        creditCardNumber:
          type: string
        creditCardOwner:
          type: string
        creditCardExpDate:
          type: string
          format: date
        creditCardSecret:
          type: string
    ProfileSettingsRequest:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        password:
          type: string
    DefaultResponse:
      type: object
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
